// Code generated by goyacc parser.go.y. DO NOT EDIT.

//line parser.go.y:2
package sakuramml

import __yyfmt__ "fmt"

//line parser.go.y:2

//line parser.go.y:5
type yySymType struct {
	yys   int
	node  *Node
	token Token
	str   string
}

const LF = 57346
const WORD = 57347
const NUMBER = 57348
const TIME = 57349
const TIME_SIG = 57350

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LF",
	"WORD",
	"NUMBER",
	"TIME",
	"TIME_SIG",
	"'c'",
	"'d'",
	"'e'",
	"'f'",
	"'g'",
	"'a'",
	"'b'",
	"'#'",
	"'+'",
	"'-'",
	"'*'",
	"'['",
	"']'",
	"':'",
	"'l'",
	"'v'",
	"'q'",
	"'o'",
	"','",
	"'('",
	"')'",
	"'@'",
	"'='",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.go.y:71

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 86

var yyAct = [...]int8{
	27, 39, 34, 36, 33, 35, 60, 52, 57, 29,
	30, 31, 32, 56, 51, 50, 37, 43, 28, 28,
	3, 38, 15, 26, 5, 4, 2, 1, 40, 41,
	42, 0, 0, 0, 44, 45, 46, 47, 0, 48,
	49, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 53, 54, 55, 0, 0, 0, 58, 59, 6,
	12, 0, 13, 14, 19, 20, 21, 22, 23, 24,
	25, 0, 0, 0, 0, 16, 17, 18, 7, 8,
	10, 9, 0, 0, 0, 11,
}

var yyPact = [...]int16{
	55, -1000, 55, -1000, -1000, -1000, -1000, 13, 13, 13,
	13, 13, -27, -26, -28, 12, 13, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 13, 13, 13, 13, -1000, 12, -1000,
	-1000, -1000, -1000, -1000, -1000, -7, -8, -20, -1000, -1000,
	13, 13, 13, -9, -14, -1000, 13, 13, -23, -1000,
	-1000,
}

var yyPgo = [...]int8{
	0, 27, 26, 20, 25, 24, 0, 22, 1, 21,
}

var yyR1 = [...]int8{
	0, 1, 2, 2, 2, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 6, 5, 5,
	5, 5, 4, 4, 4, 4, 7, 7, 7, 7,
	7, 7, 7, 9, 9, 8, 8, 8,
}

var yyR2 = [...]int8{
	0, 1, 0, 1, 2, 1, 1, 1, 2, 2,
	2, 2, 2, 3, 8, 7, 5, 1, 2, 1,
	1, 1, 2, 3, 2, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 2, 1, 1, 1,
}

var yyChk = [...]int16{
	-1000, -1, -2, -3, -4, -5, 4, 23, 24, 26,
	25, 30, 5, 7, 8, -7, 20, 21, 22, 9,
	10, 11, 12, 13, 14, 15, -3, -6, 6, -6,
	-6, -6, -6, 31, 28, 31, 31, -6, -9, -8,
	16, 17, 18, -6, -6, -6, -6, -6, -6, -8,
	22, 22, 27, -6, -6, -6, 22, 22, -6, -6,
	29,
}

var yyDef = [...]int8{
	2, -2, 1, 3, 5, 6, 7, 0, 0, 0,
	0, 0, 0, 0, 0, 25, 19, 20, 21, 26,
	27, 28, 29, 30, 31, 32, 4, 8, 17, 9,
	10, 11, 12, 0, 0, 0, 0, 22, 24, 33,
	35, 36, 37, 18, 13, 0, 0, 0, 23, 34,
	0, 0, 0, 0, 0, 16, 0, 0, 0, 15,
	14,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 16, 3, 3, 3, 3,
	28, 29, 19, 17, 27, 18, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 22, 3,
	3, 31, 3, 3, 30, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 20, 3, 21, 3, 3, 3, 14, 15, 9,
	10, 11, 12, 13, 3, 3, 3, 3, 23, 3,
	3, 26, 3, 25, 3, 3, 3, 3, 24,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:24
		{
			yyVAL.node = yyDollar[1].node
			yylex.(*Lexer).result = yyVAL.node
		}
	case 2:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:27
		{
			yyVAL.node = NewNode(Nop)
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:28
		{
			yyVAL.node = NewNode(NodeList)
			yyVAL.node = AppendChildNode(yyVAL.node, yyDollar[1].node)
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:29
		{
			yyVAL.node = AppendChildNode(yyDollar[1].node, yyDollar[2].node)
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:34
		{
			yyVAL.node = NewNode(NodeEOL)
		}
	case 8:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:35
		{
			yyVAL.node = NewCommandNode(yyDollar[1].token, "l", yyDollar[2].node)
		}
	case 9:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:36
		{
			yyVAL.node = NewCommandNode(yyDollar[1].token, "v", yyDollar[2].node)
		}
	case 10:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:37
		{
			yyVAL.node = NewCommandNode(yyDollar[1].token, "o", yyDollar[2].node)
		}
	case 11:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:38
		{
			yyVAL.node = NewCommandNode(yyDollar[1].token, "q", yyDollar[2].node)
		}
	case 12:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:39
		{
			yyVAL.node = NewCommandNode(yyDollar[1].token, "@", yyDollar[2].node)
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:40
		{
			yyVAL.node = NewCommandNode(yyDollar[1].token, "WORD", yyDollar[3].node)
		}
	case 14:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:41
		{
			yyVAL.node = NewTimeNode(yyDollar[1].token, yyDollar[3].node, yyDollar[5].node, yyDollar[7].node)
		}
	case 15:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:42
		{
			yyVAL.node = NewTimeNode(yyDollar[1].token, yyDollar[3].node, yyDollar[5].node, yyDollar[7].node)
		}
	case 16:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:43
		{
			yyVAL.node = NewTimeSigNode(yyDollar[1].token, yyDollar[3].node, yyDollar[5].node)
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:46
		{
			yyVAL.node = NewNumberNode(yyDollar[1].token)
		}
	case 18:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:49
		{
			yyVAL.node = NewLoopNodeBegin(yyDollar[1].token, yyDollar[2].node)
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:50
		{
			yyVAL.node = NewLoopNodeBegin(yyDollar[1].token, nil)
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:51
		{
			yyVAL.node = NewLoopNodeEnd(yyDollar[1].token)
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:52
		{
			yyVAL.node = NewLoopNodeBreak(yyDollar[1].token)
		}
	case 22:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:55
		{
			yyVAL.node = NewToneNode(yyDollar[1].token, "", yyDollar[2].node)
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:56
		{
			yyVAL.node = NewToneNode(yyDollar[1].token, yyDollar[2].str, yyDollar[3].node)
		}
	case 24:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:57
		{
			yyVAL.node = NewToneNode(yyDollar[1].token, yyDollar[2].str, nil)
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:58
		{
			yyVAL.node = NewToneNode(yyDollar[1].token, "", nil)
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:64
		{
			yyVAL.str = yyDollar[1].token.label
		}
	case 34:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:65
		{
			yyVAL.str = yyDollar[1].str + yyDollar[2].token.label
		}
	}
	goto yystack /* stack new state and value */
}
