// Code generated by goyacc parser.go.y. DO NOT EDIT.

//line parser.go.y:2
package mmlparser

import __yyfmt__ "fmt"

//line parser.go.y:2

//line parser.go.y:5
type yySymType struct {
	yys   int
	node  *Node
	token Token
	str   string
}
